apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/tf-controller

patches:
  - path: helmrelease.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: tf-controller
      namespace: flux-system
      version: v2beta1
